# Generated by Django 5.1.15 on 2026-09-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('CAMERA', 'Camera'), ('LAPTOP', 'Laptop'), ('SENSOR', 'Sensor'), ('VEHICLE', 'Vehicle')], max_length=16)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CHECKED_OUT', 'Checked Out'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=16)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='assets.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='assets.employee')),
            ],
            options={
                'db_table': 'checkouts',
            },
        ),
        migrations.CreateModel(
            name='OverdueNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='assets.checkout')),
            ],
            options={
                'db_table': 'overdue_notices',
                'constraints': [models.UniqueConstraint(fields=('checkout', 'notice_date'), name='unique_notice_per_checkout_date')],
            },
        ),
    ]
